# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        env > .env
        env > "my_secrets.txt"

        # echo "$SECRETS_VARS" > "my_secrets.txt"
        python -m pip install --upgrade pip
        python -m pip install python-dotenv==1.2.2
      env:
        SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
        SLACK_APP_TOKEN: "${{ secrets.SLACK_APP_TOKEN }}"
        SLACK_SIGN_SECRET: ${{ secrets.SLACK_SIGN_SECRET }}
        WORKSPACE_JOIN_TEMPLATE_PATH: ${{ secrets.WORKSPACE_JOIN_TEMPLATE_PATH }}
        GSHEET_LOG_IDS: "${{ secrets.GSHEET_LOG_IDS }}"
        GOOGLE_SERVICEKEY_JSON: "${{ secrets.GOOGLE_SERVICEKEY_JSON }}"
        SECRETS_VARS: "${{ toJson(secrets) }}"
    - name: Lint with flake8
      run: |
        # cat my_secrets.txt && 
        python app.py
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        SLACK_SIGN_SECRET: ${{ secrets.SLACK_SIGN_SECRET }}
        WORKSPACE_JOIN_TEMPLATE_PATH: ${{ secrets.WORKSPACE_JOIN_TEMPLATE_PATH }}
        GSHEET_LOG_IDS: ${{ secrets.GSHEET_LOG_IDS }}
        GOOGLE_SERVICEKEY_JSON: ${{ secrets.GOOGLE_SERVICEKEY_JSON }}
        SECRETS_VARS: ${{ toJson(secrets) }}
      
